/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	scheme "github.com/Azure/brigade/pkg/pipeline/client/clientset/versioned/scheme"
	v1 "github.com/Azure/brigade/pkg/pipeline/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PipelineComponentsGetter has a method to return a PipelineComponentInterface.
// A group's client should implement this interface.
type PipelineComponentsGetter interface {
	PipelineComponents(namespace string) PipelineComponentInterface
}

// PipelineComponentInterface has methods to work with PipelineComponent resources.
type PipelineComponentInterface interface {
	Create(*v1.PipelineComponent) (*v1.PipelineComponent, error)
	Update(*v1.PipelineComponent) (*v1.PipelineComponent, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.PipelineComponent, error)
	List(opts metav1.ListOptions) (*v1.PipelineComponentList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.PipelineComponent, err error)
	PipelineComponentExpansion
}

// pipelineComponents implements PipelineComponentInterface
type pipelineComponents struct {
	client rest.Interface
	ns     string
}

// newPipelineComponents returns a PipelineComponents
func newPipelineComponents(c *PipelineV1Client, namespace string) *pipelineComponents {
	return &pipelineComponents{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the pipelineComponent, and returns the corresponding pipelineComponent object, and an error if there is any.
func (c *pipelineComponents) Get(name string, options metav1.GetOptions) (result *v1.PipelineComponent, err error) {
	result = &v1.PipelineComponent{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pipelinecomponents").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PipelineComponents that match those selectors.
func (c *pipelineComponents) List(opts metav1.ListOptions) (result *v1.PipelineComponentList, err error) {
	result = &v1.PipelineComponentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pipelinecomponents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pipelineComponents.
func (c *pipelineComponents) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("pipelinecomponents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a pipelineComponent and creates it.  Returns the server's representation of the pipelineComponent, and an error, if there is any.
func (c *pipelineComponents) Create(pipelineComponent *v1.PipelineComponent) (result *v1.PipelineComponent, err error) {
	result = &v1.PipelineComponent{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("pipelinecomponents").
		Body(pipelineComponent).
		Do().
		Into(result)
	return
}

// Update takes the representation of a pipelineComponent and updates it. Returns the server's representation of the pipelineComponent, and an error, if there is any.
func (c *pipelineComponents) Update(pipelineComponent *v1.PipelineComponent) (result *v1.PipelineComponent, err error) {
	result = &v1.PipelineComponent{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pipelinecomponents").
		Name(pipelineComponent.Name).
		Body(pipelineComponent).
		Do().
		Into(result)
	return
}

// Delete takes name of the pipelineComponent and deletes it. Returns an error if one occurs.
func (c *pipelineComponents) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pipelinecomponents").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pipelineComponents) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pipelinecomponents").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched pipelineComponent.
func (c *pipelineComponents) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.PipelineComponent, err error) {
	result = &v1.PipelineComponent{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("pipelinecomponents").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
