/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	scheme "github.com/Azure/brigade/pkg/pipeline/client/clientset/versioned/scheme"
	v1 "github.com/Azure/brigade/pkg/pipeline/v1"
)

// PipelineDefinitionsGetter has a method to return a PipelineDefinitionInterface.
// A group's client should implement this interface.
type PipelineDefinitionsGetter interface {
	PipelineDefinitions(namespace string) PipelineDefinitionInterface
}

// PipelineDefinitionInterface has methods to work with PipelineDefinition resources.
type PipelineDefinitionInterface interface {
	Create(*v1.PipelineDefinition) (*v1.PipelineDefinition, error)
	Update(*v1.PipelineDefinition) (*v1.PipelineDefinition, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.PipelineDefinition, error)
	List(opts metav1.ListOptions) (*v1.PipelineDefinitionList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.PipelineDefinition, err error)
	PipelineDefinitionExpansion
}

// pipelineDefinitions implements PipelineDefinitionInterface
type pipelineDefinitions struct {
	client rest.Interface
	ns     string
}

// newPipelineDefinitions returns a PipelineDefinitions
func newPipelineDefinitions(c *PipelineV1Client, namespace string) *pipelineDefinitions {
	return &pipelineDefinitions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the pipelineDefinition, and returns the corresponding pipelineDefinition object, and an error if there is any.
func (c *pipelineDefinitions) Get(name string, options metav1.GetOptions) (result *v1.PipelineDefinition, err error) {
	result = &v1.PipelineDefinition{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pipelinedefinitions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PipelineDefinitions that match those selectors.
func (c *pipelineDefinitions) List(opts metav1.ListOptions) (result *v1.PipelineDefinitionList, err error) {
	result = &v1.PipelineDefinitionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pipelinedefinitions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pipelineDefinitions.
func (c *pipelineDefinitions) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("pipelinedefinitions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a pipelineDefinition and creates it.  Returns the server's representation of the pipelineDefinition, and an error, if there is any.
func (c *pipelineDefinitions) Create(pipelineDefinition *v1.PipelineDefinition) (result *v1.PipelineDefinition, err error) {
	result = &v1.PipelineDefinition{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("pipelinedefinitions").
		Body(pipelineDefinition).
		Do().
		Into(result)
	return
}

// Update takes the representation of a pipelineDefinition and updates it. Returns the server's representation of the pipelineDefinition, and an error, if there is any.
func (c *pipelineDefinitions) Update(pipelineDefinition *v1.PipelineDefinition) (result *v1.PipelineDefinition, err error) {
	result = &v1.PipelineDefinition{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pipelinedefinitions").
		Name(pipelineDefinition.Name).
		Body(pipelineDefinition).
		Do().
		Into(result)
	return
}

// Delete takes name of the pipelineDefinition and deletes it. Returns an error if one occurs.
func (c *pipelineDefinitions) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pipelinedefinitions").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pipelineDefinitions) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pipelinedefinitions").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched pipelineDefinition.
func (c *pipelineDefinitions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.PipelineDefinition, err error) {
	result = &v1.PipelineDefinition{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("pipelinedefinitions").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
