# yaml-language-server: $schema=https://raw.githubusercontent.com/brigadecore/brigade/v2/v2/apiserver/schemas/project.json
apiVersion: brigade.sh/v2-alpha.4
kind: Project
metadata:
  id: shared-workspace
description: Demonstrates a workspace shared across jobs
spec:
  workerTemplate:
    logLevel: DEBUG
    useWorkspace: true
    defaultConfigFiles:
      brigade.js: | 
        const { events, Job } = require("@brigadecore/brigadier");

        events.on("brigade.sh/cli", "exec", async event => {
          let job1 = new Job("first-job", "debian:latest", event);
          job1.primaryContainer.workspaceMountPath = "/share";
          job1.primaryContainer.command = ["bash"];
          job1.primaryContainer.arguments = ["-c", "echo 'Hello!' > /share/message"];
          await job1.run();

          let job2 = new Job("second-job", "debian:latest", event);
          job2.primaryContainer.workspaceMountPath = "/share";
          job2.primaryContainer.command = ["cat"];
          job2.primaryContainer.arguments = ["/share/message"];
          await job2.run();
        });

        events.process();
