apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brigade.observer.fullname" . }}
  labels:
    {{- include "brigade.labels" . | nindent 4 }}
    {{- include "brigade.observer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Release.IsInstall }}
  # Auto-generate a random string on install
  api-token: {{ randAlphaNum 30 }}
  {{- else }}
  # For any subsequent release upgrade, retrieve the data from the pre-existing secret
  {{- $data := (lookup "v1" "Secret" .Release.Namespace (include "brigade.observer.fullname" . )).data }}
  # This check is just to pass chart linting when no actual resources are created
  {{- if $data }}
  api-token: {{ b64dec (index $data "api-token") }}
  {{- end }}
  {{- end }}
