package main

import (
	"testing"
)

func TestShortSha(t *testing.T) {
	// The expect line was generated by the macOS shasum command, which adds
	// a trailing newline. Note truncated at 54 chars.
	str := "I Break For Sea Beasts\n"
	// c635ce8f0388d039ac9a01d60cfb362dbca8e0722000b614bee75e8e3063621f
	expect := "c635ce8f0388d039ac9a01d60cfb362dbca8e0722000b614bee75e"
	if got := shortSha(str); got != expect {
		t.Fatalf("Expected short SHA\n\t%q, got\n\t%q", expect, got)
	}
}

func TestSaltedSha11Sum(t *testing.T) {
	// The expect line was computed with this command:
	// $ echo "This is the way the world ends.Not with a bang, but a whimper." | shasum -a 1
	salt := []byte("This is the way the world ends.")
	message := []byte("Not with a bang, but a whimper.\n")
	expect := "239a4a7c96c3f04ffea7f785d03fb21901565e26"
	if got := saltedSha1Sum(salt, message); got != expect {
		t.Fatalf("Expected \n\t%q, got\n\t%q", expect, got)
	}
}
