package main

import (
	"testing"
)

func TestShortSha(t *testing.T) {
	// The expect line was generated by the macOS shasum command, which adds
	// a trailing newline. Note truncated at 54 chars.
	str := "I Break For Sea Beasts\n"
	// c635ce8f0388d039ac9a01d60cfb362dbca8e0722000b614bee75e8e3063621f
	expect := "c635ce8f0388d039ac9a01d60cfb362dbca8e0722000b614bee75e"
	if got := shortSha(str); got != expect {
		t.Fatalf("Expected short SHA\n\t%q, got\n\t%q", expect, got)
	}
}

func TestSha1HMAC(t *testing.T) {
	salt := []byte("This is the way the world ends.")
	message := []byte("Not with a bang, but a whimper.\n")
	expect := "sha1=0ca6713b350828f53c6dcced9232aeace3e60708"
	if got := sha1HMAC(salt, message); got != expect {
		t.Fatalf("Expected \n\t%q, got\n\t%q", expect, got)
	}
}
