# yaml-language-server: $schema=https://schemas.brigade.sh/schemas-v2/project.json
apiVersion: brigade.sh/v2
kind: Project
metadata:
  id: windows
description: Demonstrates a Windows-based job
spec:
  eventSubscriptions:
  - source: brigade.sh/cli
    types:
    - exec
  workerTemplate:
    # logLevel: DEBUG
    defaultConfigFiles:
      brigade.js: |
        const { events, Job } = require("@brigadecore/brigadier");

        events.on("brigade.sh/cli", "exec", async event => {
          let job = new Job("hello", "mcr.microsoft.com/windows/nanoserver:1809", event);
          job.primaryContainer.command = ["cmd.exe"];
          job.primaryContainer.arguments = ["/k", "echo Hello from Windows!"];
          job.host = {
            os: "windows"
          };
          await job.run();
        });

        events.process();
