/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
	pipelinev1 "github.com/Azure/brigade/pkg/pipeline/v1"
=======
	radixv1 "github.com/Azure/brigade/pkg/pipeline/v1"
>>>>>>> 0d0313d... added crd types
=======
	pipelinev1 "github.com/Azure/brigade/pkg/pipeline/v1"
>>>>>>> ccd1e53... started on brig pipeline functionality. more types work.
=======
>>>>>>> 6bb4934... fixed linting issues
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	serializer "k8s.io/apimachinery/pkg/runtime/serializer"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"

	pipelinev1 "github.com/Azure/brigade/pkg/pipeline/v1"
)

var scheme = runtime.NewScheme()
var codecs = serializer.NewCodecFactory(scheme)
var parameterCodec = runtime.NewParameterCodec(scheme)
var localSchemeBuilder = runtime.SchemeBuilder{
<<<<<<< HEAD
<<<<<<< HEAD
	pipelinev1.AddToScheme,
=======
	radixv1.AddToScheme,
>>>>>>> 0d0313d... added crd types
=======
	pipelinev1.AddToScheme,
>>>>>>> ccd1e53... started on brig pipeline functionality. more types work.
}

// AddToScheme adds all types of this clientset into the given scheme. This allows composition
// of clientsets, like in:
//
//   import (
//     "k8s.io/client-go/kubernetes"
//     clientsetscheme "k8s.io/client-go/kubernetes/scheme"
//     aggregatorclientsetscheme "k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme"
//   )
//
//   kclientset, _ := kubernetes.NewForConfig(c)
//   _ = aggregatorclientsetscheme.AddToScheme(clientsetscheme.Scheme)
//
// After this, RawExtensions in Kubernetes types will serialize kube-aggregator types
// correctly.
var AddToScheme = localSchemeBuilder.AddToScheme

func init() {
	v1.AddToGroupVersion(scheme, schema.GroupVersion{Version: "v1"})
	utilruntime.Must(AddToScheme(scheme))
}
