# yaml-language-server: $schema=https://schemas.brigade.sh/schemas-v2/project.json
apiVersion: brigade.sh/v2
kind: Project
metadata:
  id: example-gateway-project
description: |-
  An example project that subscribes to events from an example gateway
spec:
  eventSubscriptions:
  - source: example.org/example-gateway
    types:
      - hello
  workerTemplate:
    logLevel: DEBUG
    defaultConfigFiles:
      brigade.ts: |
        import { events } from "@brigadecore/brigadier"

        events.on("example.org/example-gateway", "hello", async event => {
          console.log("Hello, " + event.payload + "!")
        })

        events.process()
