package brigade

import "testing"

func TestShortSHA(t *testing.T) {
	// The expect line was generated by the macOS shasum command, which adds
	// a trailing newline. Note truncated at 54 chars.
	str := "I Break For Sea Beasts\n"
	// c635ce8f0388d039ac9a01d60cfb362dbca8e0722000b614bee75e8e3063621f
	expect := "c635ce8f0388d039ac9a01d60cfb362dbca8e0722000b614bee75e"
	if got := shortSHA(str); got != expect {
		t.Fatalf("Expected short SHA\n\t%q, got\n\t%q", expect, got)
	}
}
