# yaml-language-server: $schema=https://raw.githubusercontent.com/brigadecore/brigade/v2/v2/apiserver/schemas/project.json
apiVersion: brigade.sh/v2-alpha.2
kind: Project
metadata:
  id: simple-pipeline
description: Demonstrates a simple pipeline with brigadier
spec:
  workerTemplate:
    logLevel: DEBUG
    defaultConfigFiles:
      brigade.js: | 
        const { events, Job } = require("@brigadecore/brigadier");

        events.on("brigade.sh/cli", "exec", async event => {
          let job1 = new Job("my-first-job", "debian:latest", event);
          job1.primaryContainer.command = ["echo"];
          job1.primaryContainer.arguments = ["My first job!"];
          await job1.run();

          let job2 = new Job("my-second-job", "debian:latest", event);
          job2.primaryContainer.command = ["echo"];
          job2.primaryContainer.arguments = ["My second job!"];
          await job2.run();
        });

        events.process();
