FROM arm64v8/node:8-alpine
ADD https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-2/x86_64_qemu-aarch64-static.tar.gz /usr/bin

WORKDIR /home/src
COPY . /home/src
RUN yarn install && yarn build

CMD yarn run test
