{{- if and .Values.apiserver.ingress.enabled .Values.apiserver.ingress.tls.enabled (or .Values.apiserver.ingress.tls.generateSelfSignedCert .Values.apiserver.ingress.tls.cert) }}
{{- $apiServerTLSCert := "" }}
{{- $apiServerTLSKey := "" }}
{{- if .Values.apiserver.ingress.tls.generateSelfSignedCert }}
  {{- $data := (lookup "v1" "Secret" .Release.Namespace (printf "%s-ingress-cert" (include "brigade.apiserver.fullname" . ))).data }}
  {{- if $data }}
    # Reuse the existing cert and key
    {{- $apiServerTLSCert = index $data "tls.crt" }}
    {{- $apiServerTLSKey = index $data "tls.key" }}
  {{- else }}
    # Generate a new cert and key
    {{- $cert := genSelfSignedCert .Values.apiserver.host nil (list .Values.apiserver.host) 3650 }}
    {{- $apiServerTLSCert = b64enc $cert.Cert }}
    {{- $apiServerTLSKey = b64enc $cert.Key }}
  {{- end }}
{{- else if .Values.apiserver.ingress.tls.cert }}
  # Use operator supplied cert and key
  {{- $apiServerTLSCert = .Values.apiserver.ingress.tls.cert }}
  {{- $apiServerTLSKey = .Values.apiserver.ingress.tls.key }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brigade.apiserver.fullname" . }}-ingress-cert
  labels:
    {{- include "brigade.labels" . | nindent 4 }}
    {{- include "brigade.apiserver.labels" . | nindent 4 }}
type: Opaque
data:
  tls.crt: {{ $apiServerTLSCert }}
  tls.key: {{ $apiServerTLSKey }}
{{- end }}
