# yaml-language-server: $schema=https://raw.githubusercontent.com/brigadecore/brigade/v2/v2/apiserver/schemas/project.json
apiVersion: brigade.sh/v2-alpha.5
kind: Project
metadata:
  id: brigade
description: Brigade 2 built with Brigade 2!
spec:
  eventSubscriptions:
  - source: brigade.sh/github
    qualifiers:
      repo: brigadecore/brigade
    types:
    - check_run:rerequested
    - check_suite:requested
    - check_suite:rerequested
  workerTemplate:
    git:
      cloneURL: https://github.com/brigadecore/brigade.git
