/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 9bf0216... more work on pipeline types
// PipelineListerExpansion allows custom methods to be added to
// PipelineLister.
type PipelineListerExpansion interface{}

// PipelineNamespaceListerExpansion allows custom methods to be added to
// PipelineNamespaceLister.
type PipelineNamespaceListerExpansion interface{}

<<<<<<< HEAD
=======
>>>>>>> 0d0313d... added crd types
=======
>>>>>>> 9bf0216... more work on pipeline types
// PipelineComponentListerExpansion allows custom methods to be added to
// PipelineComponentLister.
type PipelineComponentListerExpansion interface{}

// PipelineComponentNamespaceListerExpansion allows custom methods to be added to
// PipelineComponentNamespaceLister.
type PipelineComponentNamespaceListerExpansion interface{}
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> ccd1e53... started on brig pipeline functionality. more types work.

// PipelineDefinitionListerExpansion allows custom methods to be added to
// PipelineDefinitionLister.
type PipelineDefinitionListerExpansion interface{}

// PipelineDefinitionNamespaceListerExpansion allows custom methods to be added to
// PipelineDefinitionNamespaceLister.
type PipelineDefinitionNamespaceListerExpansion interface{}
<<<<<<< HEAD
=======
>>>>>>> 0d0313d... added crd types
=======
>>>>>>> ccd1e53... started on brig pipeline functionality. more types work.
