FROM arm64v8/alpine:3.8
ADD https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-2/x86_64_qemu-aarch64-static.tar.gz /usr/bin

RUN apk update && apk add --no-cache \
  ca-certificates \
  git \
  && update-ca-certificates

COPY rootfs/arm64/brigade-generic-gateway /usr/bin/brigade-generic-gateway

CMD /usr/bin/brigade-generic-gateway
