package storage

import (
	"testing"

	"github.com/deis/acid/pkg/acid"
)

func TestConfigureProject(t *testing.T) {
	data := map[string][]byte{
		"repository":   []byte("myrepo"),
		"sharedSecret": []byte("mysecret"),
		"githubToken":  []byte("like a fish needs a bicycle"),
		"sshKey":       []byte("hello$world"),
		"namespace":    []byte("zooropa"),
		"secrets":      []byte(`{"bar":"baz","foo":"bar"}`),
		// Intentionally skip cloneURL, test that this is ""
	}
	proj := &acid.Project{Name: "acidTest"}
	if err := configureProject(proj, data, "defaultNS"); err != nil {
		t.Fatal(err)
	}

	if proj.Repo.CloneURL != "" {
		t.Errorf("Expected empty cloneURL, got %s", proj.Repo.CloneURL)
	}

	if proj.Repo.Name != "myrepo" {
		t.Error("Repo is not correct")
	}
	if proj.SharedSecret != "mysecret" {
		t.Error("SharedSecret is not correct")
	}
	if proj.GitHubToken != "like a fish needs a bicycle" {
		t.Error("Fish cannot find its bicycle")
	}
	if proj.Repo.SSHKey != "hello\nworld" {
		t.Errorf("Unexpected SSHKey: %q", proj.Repo.SSHKey)
	}
	if v, ok := proj.Secrets["bar"]; !ok {
		t.Error("Could not find key bar in Secrets")
	} else if v != "baz" {
		t.Errorf("Expected baz, got %q", v)
	}
	if v, ok := proj.Secrets["NO SUCH KEY"]; ok {
		t.Fatal("unexpected key")
	} else if v != "" {
		t.Fatal("Expected empty string for non-existent key")
	}
}

func TestDef(t *testing.T) {
	if got := def([]byte{}, "default"); got != "default" {
		t.Error("Expected default value")
	}
	if got := def([]byte("hello"), "world"); got != "hello" {
		t.Error("Expected non-default value")
	}
}

func TestShortSHA(t *testing.T) {
	// The expect line was generated by the macOS shasum command, which adds
	// a trailing newline. Note truncated at 54 chars.
	str := "I Break For Sea Beasts\n"
	// c635ce8f0388d039ac9a01d60cfb362dbca8e0722000b614bee75e8e3063621f
	expect := "c635ce8f0388d039ac9a01d60cfb362dbca8e0722000b614bee75e"
	if got := shortSHA(str); got != expect {
		t.Fatalf("Expected short SHA\n\t%q, got\n\t%q", expect, got)
	}
}
