# yaml-language-server: $schema=https://schemas.brigade.sh/schemas-v2/project.json
apiVersion: brigade.sh/v2
kind: Project
metadata:
  id: first-payload
description: Demonstrates using the event payload
spec:
  eventSubscriptions:
  - source: brigade.sh/cli
    types:
    - exec
  workerTemplate:
    # logLevel: DEBUG
    defaultConfigFiles:
      brigade.js: | 
        const { events } = require("@brigadecore/brigadier");

        events.on("brigade.sh/cli", "exec", async event => {
          console.log("Project: " + event.project.id);
          console.log("Hello, " + event.payload + "!");
        });

        events.process();
