/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	pipelinev1 "github.com/Azure/brigade/pkg/pipeline/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePipelineComponents implements PipelineComponentInterface
type FakePipelineComponents struct {
	Fake *FakePipelineV1
	ns   string
}

var pipelinecomponentsResource = schema.GroupVersionResource{Group: "pipeline.brigade.io", Version: "v1", Resource: "pipelinecomponents"}

var pipelinecomponentsKind = schema.GroupVersionKind{Group: "pipeline.brigade.io", Version: "v1", Kind: "PipelineComponent"}

// Get takes name of the pipelineComponent, and returns the corresponding pipelineComponent object, and an error if there is any.
func (c *FakePipelineComponents) Get(name string, options v1.GetOptions) (result *pipelinev1.PipelineComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pipelinecomponentsResource, c.ns, name), &pipelinev1.PipelineComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pipelinev1.PipelineComponent), err
}

// List takes label and field selectors, and returns the list of PipelineComponents that match those selectors.
func (c *FakePipelineComponents) List(opts v1.ListOptions) (result *pipelinev1.PipelineComponentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pipelinecomponentsResource, pipelinecomponentsKind, c.ns, opts), &pipelinev1.PipelineComponentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &pipelinev1.PipelineComponentList{ListMeta: obj.(*pipelinev1.PipelineComponentList).ListMeta}
	for _, item := range obj.(*pipelinev1.PipelineComponentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pipelineComponents.
func (c *FakePipelineComponents) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pipelinecomponentsResource, c.ns, opts))

}

// Create takes the representation of a pipelineComponent and creates it.  Returns the server's representation of the pipelineComponent, and an error, if there is any.
func (c *FakePipelineComponents) Create(pipelineComponent *pipelinev1.PipelineComponent) (result *pipelinev1.PipelineComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pipelinecomponentsResource, c.ns, pipelineComponent), &pipelinev1.PipelineComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pipelinev1.PipelineComponent), err
}

// Update takes the representation of a pipelineComponent and updates it. Returns the server's representation of the pipelineComponent, and an error, if there is any.
func (c *FakePipelineComponents) Update(pipelineComponent *pipelinev1.PipelineComponent) (result *pipelinev1.PipelineComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pipelinecomponentsResource, c.ns, pipelineComponent), &pipelinev1.PipelineComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pipelinev1.PipelineComponent), err
}

// Delete takes name of the pipelineComponent and deletes it. Returns an error if one occurs.
func (c *FakePipelineComponents) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(pipelinecomponentsResource, c.ns, name), &pipelinev1.PipelineComponent{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePipelineComponents) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pipelinecomponentsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &pipelinev1.PipelineComponentList{})
	return err
}

// Patch applies the patch and returns the patched pipelineComponent.
func (c *FakePipelineComponents) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *pipelinev1.PipelineComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pipelinecomponentsResource, c.ns, name, data, subresources...), &pipelinev1.PipelineComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pipelinev1.PipelineComponent), err
}
