/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	pipelinev1 "github.com/Azure/brigade/pkg/pipeline/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePipelineDefinitions implements PipelineDefinitionInterface
type FakePipelineDefinitions struct {
	Fake *FakePipelineV1
	ns   string
}

var pipelinedefinitionsResource = schema.GroupVersionResource{Group: "pipeline.brigade.sh", Version: "v1", Resource: "pipelinedefinitions"}

var pipelinedefinitionsKind = schema.GroupVersionKind{Group: "pipeline.brigade.sh", Version: "v1", Kind: "PipelineDefinition"}

// Get takes name of the pipelineDefinition, and returns the corresponding pipelineDefinition object, and an error if there is any.
func (c *FakePipelineDefinitions) Get(name string, options v1.GetOptions) (result *pipelinev1.PipelineDefinition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pipelinedefinitionsResource, c.ns, name), &pipelinev1.PipelineDefinition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pipelinev1.PipelineDefinition), err
}

// List takes label and field selectors, and returns the list of PipelineDefinitions that match those selectors.
func (c *FakePipelineDefinitions) List(opts v1.ListOptions) (result *pipelinev1.PipelineDefinitionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pipelinedefinitionsResource, pipelinedefinitionsKind, c.ns, opts), &pipelinev1.PipelineDefinitionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &pipelinev1.PipelineDefinitionList{ListMeta: obj.(*pipelinev1.PipelineDefinitionList).ListMeta}
	for _, item := range obj.(*pipelinev1.PipelineDefinitionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pipelineDefinitions.
func (c *FakePipelineDefinitions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pipelinedefinitionsResource, c.ns, opts))

}

// Create takes the representation of a pipelineDefinition and creates it.  Returns the server's representation of the pipelineDefinition, and an error, if there is any.
func (c *FakePipelineDefinitions) Create(pipelineDefinition *pipelinev1.PipelineDefinition) (result *pipelinev1.PipelineDefinition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pipelinedefinitionsResource, c.ns, pipelineDefinition), &pipelinev1.PipelineDefinition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pipelinev1.PipelineDefinition), err
}

// Update takes the representation of a pipelineDefinition and updates it. Returns the server's representation of the pipelineDefinition, and an error, if there is any.
func (c *FakePipelineDefinitions) Update(pipelineDefinition *pipelinev1.PipelineDefinition) (result *pipelinev1.PipelineDefinition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pipelinedefinitionsResource, c.ns, pipelineDefinition), &pipelinev1.PipelineDefinition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pipelinev1.PipelineDefinition), err
}

// Delete takes name of the pipelineDefinition and deletes it. Returns an error if one occurs.
func (c *FakePipelineDefinitions) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(pipelinedefinitionsResource, c.ns, name), &pipelinev1.PipelineDefinition{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePipelineDefinitions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pipelinedefinitionsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &pipelinev1.PipelineDefinitionList{})
	return err
}

// Patch applies the patch and returns the patched pipelineDefinition.
func (c *FakePipelineDefinitions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *pipelinev1.PipelineDefinition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pipelinedefinitionsResource, c.ns, name, data, subresources...), &pipelinev1.PipelineDefinition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pipelinev1.PipelineDefinition), err
}
