name: Brigade Merge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    env:
      DOCKER_ORG: brigadecore
    steps:
      - uses: actions/checkout@main
      - name: Build Windows logger agent
        run: make build-logger-windows
      - name: Build Windows git initializer
        run: make build-git-initializer-windows
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Windows logger agent
        run: make push-logger-windows
      - name: Push Windows git initializer
        run: make push-git-initializer-windows
