name: Brigade v2 Release

on:
  push:
    tags:
      - v2.*.*

jobs:
  build:
    runs-on: windows-latest
    env:
      DOCKER_ORG: brigadecore
    steps:
      - uses: actions/checkout@v2
      - name: Build Windows logger agent
        run: make build-logger-windows
      - name: Build Windows git initializer
        run: make build-git-initializer-windows
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Windows logger agent
        run: VERSION=${GITHUB_REF:10} make push-logger-windows
      - name: Push Windows git initializer
        run: VERSION=${GITHUB_REF:10} make push-git-initializer-windows
