name: Brigade Release

on:
  push:
    tags:
      - v2.*.*

jobs:
  build:
    runs-on: windows-2019
    env:
      DOCKER_ORG: brigadecore
    steps:
      - uses: actions/checkout@main
      - name: Build Windows logger agent
        run: $env:VERSION=$env:GITHUB_REF.substring(10, $env:GITHUB_REF.length-10); make build-logger-windows
      - name: Build Windows git initializer
        run: $env:VERSION=$env:GITHUB_REF.substring(10, $env:GITHUB_REF.length-10); make build-git-initializer-windows
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Windows logger agent
        run: $env:VERSION=$env:GITHUB_REF.substring(10, $env:GITHUB_REF.length-10); make push-logger-windows
      - name: Push Windows git initializer
        run: $env:VERSION=$env:GITHUB_REF.substring(10, $env:GITHUB_REF.length-10); make push-git-initializer-windows
